import { StyleSheet } from "react-native";
import { PrimeWhite } from "../../constants/styles.constants";

export const commonStyles = StyleSheet.create({
  pb10: { paddingBottom: 10 },
  pb20: { paddingBottom: 20 },
  pt10: { paddingTop: 10 },
  pt20: { paddingTop: 20 },
  pr20: { paddingRight: 20 },
  pr10: { paddingRight: 10 },
  pr5: { paddingRight: 5 },
  pl20: { paddingLeft: 20 },
  pl10: { paddingLeft: 10 },
  pl5: { paddingLeft: 5 },
  mt20: { marginTop: 20 },
  mt15: { marginTop: 15 },
  mt10: { marginTop: 10 },
  mb5: { marginBottom: 5 },
  mb10: { marginBottom: 10 },
  mb15: { marginBottom: 15 },
  mr20: { marginRight: 20 },
  mr0: { marginRight: 0 },
  ml10: { marginLeft: 10 },
  ml20: { marginLeft: 20 },
  mb20: { marginBottom: 20 },
  bottomIcon: { marginBottom: -3, fontSize: 22 },
  transparent: { backgroundColor: "transparent" },
  whiteBackground: { backgroundColor: PrimeWhite },
  containerView: {
    flex: 1,
    backgroundColor: PrimeWhite,
    padding: 10,
    margin: 10,
    borderRadius: 6,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
});
